version: "3.9"
services:
  backend:
    build: .
    ports:
      - 7070:3030
    volumes:
      - .:/app
    depends_on: # 이하의 컨테이너들을 먼저 실행
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
